// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

// Protobuf Java Version: 3.25.7
package com.hooniegit.NettyDataProtocol.Protobuf;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TagDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hooniegit.NettyDataProtocol.Protobuf.TagData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>int32 int_value = 2;</code>
     * @return Whether the intValue field is set.
     */
    boolean hasIntValue();
    /**
     * <code>int32 int_value = 2;</code>
     * @return The intValue.
     */
    int getIntValue();

    /**
     * <code>double double_value = 3;</code>
     * @return Whether the doubleValue field is set.
     */
    boolean hasDoubleValue();
    /**
     * <code>double double_value = 3;</code>
     * @return The doubleValue.
     */
    double getDoubleValue();

    /**
     * <code>string string_value = 4;</code>
     * @return Whether the stringValue field is set.
     */
    boolean hasStringValue();
    /**
     * <code>string string_value = 4;</code>
     * @return The stringValue.
     */
    java.lang.String getStringValue();
    /**
     * <code>string string_value = 4;</code>
     * @return The bytes for stringValue.
     */
    com.google.protobuf.ByteString
        getStringValueBytes();

    /**
     * <code>bool bool_value = 5;</code>
     * @return Whether the boolValue field is set.
     */
    boolean hasBoolValue();
    /**
     * <code>bool bool_value = 5;</code>
     * @return The boolValue.
     */
    boolean getBoolValue();

    /**
     * <code>bytes raw_value = 6;</code>
     * @return Whether the rawValue field is set.
     */
    boolean hasRawValue();
    /**
     * <code>bytes raw_value = 6;</code>
     * @return The rawValue.
     */
    com.google.protobuf.ByteString getRawValue();

    com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData.ValueCase getValueCase();
  }
  /**
   * Protobuf type {@code com.hooniegit.NettyDataProtocol.Protobuf.TagData}
   */
  public static final class TagData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hooniegit.NettyDataProtocol.Protobuf.TagData)
      TagDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TagData.newBuilder() to construct.
    private TagData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TagData() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TagData();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hooniegit.NettyDataProtocol.Protobuf.Message.internal_static_com_hooniegit_protobuf_TagData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hooniegit.NettyDataProtocol.Protobuf.Message.internal_static_com_hooniegit_protobuf_TagData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData.class, com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData.Builder.class);
    }

    private int valueCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object value_;
    public enum ValueCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      INT_VALUE(2),
      DOUBLE_VALUE(3),
      STRING_VALUE(4),
      BOOL_VALUE(5),
      RAW_VALUE(6),
      VALUE_NOT_SET(0);
      private final int value;
      private ValueCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ValueCase valueOf(int value) {
        return forNumber(value);
      }

      public static ValueCase forNumber(int value) {
        switch (value) {
          case 2: return INT_VALUE;
          case 3: return DOUBLE_VALUE;
          case 4: return STRING_VALUE;
          case 5: return BOOL_VALUE;
          case 6: return RAW_VALUE;
          case 0: return VALUE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ValueCase
    getValueCase() {
      return ValueCase.forNumber(
          valueCase_);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int INT_VALUE_FIELD_NUMBER = 2;
    /**
     * <code>int32 int_value = 2;</code>
     * @return Whether the intValue field is set.
     */
    @java.lang.Override
    public boolean hasIntValue() {
      return valueCase_ == 2;
    }
    /**
     * <code>int32 int_value = 2;</code>
     * @return The intValue.
     */
    @java.lang.Override
    public int getIntValue() {
      if (valueCase_ == 2) {
        return (java.lang.Integer) value_;
      }
      return 0;
    }

    public static final int DOUBLE_VALUE_FIELD_NUMBER = 3;
    /**
     * <code>double double_value = 3;</code>
     * @return Whether the doubleValue field is set.
     */
    @java.lang.Override
    public boolean hasDoubleValue() {
      return valueCase_ == 3;
    }
    /**
     * <code>double double_value = 3;</code>
     * @return The doubleValue.
     */
    @java.lang.Override
    public double getDoubleValue() {
      if (valueCase_ == 3) {
        return (java.lang.Double) value_;
      }
      return 0D;
    }

    public static final int STRING_VALUE_FIELD_NUMBER = 4;
    /**
     * <code>string string_value = 4;</code>
     * @return Whether the stringValue field is set.
     */
    public boolean hasStringValue() {
      return valueCase_ == 4;
    }
    /**
     * <code>string string_value = 4;</code>
     * @return The stringValue.
     */
    public java.lang.String getStringValue() {
      java.lang.Object ref = "";
      if (valueCase_ == 4) {
        ref = value_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (valueCase_ == 4) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string string_value = 4;</code>
     * @return The bytes for stringValue.
     */
    public com.google.protobuf.ByteString
        getStringValueBytes() {
      java.lang.Object ref = "";
      if (valueCase_ == 4) {
        ref = value_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (valueCase_ == 4) {
          value_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOOL_VALUE_FIELD_NUMBER = 5;
    /**
     * <code>bool bool_value = 5;</code>
     * @return Whether the boolValue field is set.
     */
    @java.lang.Override
    public boolean hasBoolValue() {
      return valueCase_ == 5;
    }
    /**
     * <code>bool bool_value = 5;</code>
     * @return The boolValue.
     */
    @java.lang.Override
    public boolean getBoolValue() {
      if (valueCase_ == 5) {
        return (java.lang.Boolean) value_;
      }
      return false;
    }

    public static final int RAW_VALUE_FIELD_NUMBER = 6;
    /**
     * <code>bytes raw_value = 6;</code>
     * @return Whether the rawValue field is set.
     */
    @java.lang.Override
    public boolean hasRawValue() {
      return valueCase_ == 6;
    }
    /**
     * <code>bytes raw_value = 6;</code>
     * @return The rawValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRawValue() {
      if (valueCase_ == 6) {
        return (com.google.protobuf.ByteString) value_;
      }
      return com.google.protobuf.ByteString.EMPTY;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (valueCase_ == 2) {
        output.writeInt32(
            2, (int)((java.lang.Integer) value_));
      }
      if (valueCase_ == 3) {
        output.writeDouble(
            3, (double)((java.lang.Double) value_));
      }
      if (valueCase_ == 4) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, value_);
      }
      if (valueCase_ == 5) {
        output.writeBool(
            5, (boolean)((java.lang.Boolean) value_));
      }
      if (valueCase_ == 6) {
        output.writeBytes(
            6, (com.google.protobuf.ByteString) value_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (valueCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(
              2, (int)((java.lang.Integer) value_));
      }
      if (valueCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(
              3, (double)((java.lang.Double) value_));
      }
      if (valueCase_ == 4) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, value_);
      }
      if (valueCase_ == 5) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(
              5, (boolean)((java.lang.Boolean) value_));
      }
      if (valueCase_ == 6) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(
              6, (com.google.protobuf.ByteString) value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData)) {
        return super.equals(obj);
      }
      com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData other = (com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData) obj;

      if (getId()
          != other.getId()) return false;
      if (!getValueCase().equals(other.getValueCase())) return false;
      switch (valueCase_) {
        case 2:
          if (getIntValue()
              != other.getIntValue()) return false;
          break;
        case 3:
          if (java.lang.Double.doubleToLongBits(getDoubleValue())
              != java.lang.Double.doubleToLongBits(
                  other.getDoubleValue())) return false;
          break;
        case 4:
          if (!getStringValue()
              .equals(other.getStringValue())) return false;
          break;
        case 5:
          if (getBoolValue()
              != other.getBoolValue()) return false;
          break;
        case 6:
          if (!getRawValue()
              .equals(other.getRawValue())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      switch (valueCase_) {
        case 2:
          hash = (37 * hash) + INT_VALUE_FIELD_NUMBER;
          hash = (53 * hash) + getIntValue();
          break;
        case 3:
          hash = (37 * hash) + DOUBLE_VALUE_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              java.lang.Double.doubleToLongBits(getDoubleValue()));
          break;
        case 4:
          hash = (37 * hash) + STRING_VALUE_FIELD_NUMBER;
          hash = (53 * hash) + getStringValue().hashCode();
          break;
        case 5:
          hash = (37 * hash) + BOOL_VALUE_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
              getBoolValue());
          break;
        case 6:
          hash = (37 * hash) + RAW_VALUE_FIELD_NUMBER;
          hash = (53 * hash) + getRawValue().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hooniegit.NettyDataProtocol.Protobuf.TagData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hooniegit.NettyDataProtocol.Protobuf.TagData)
        com.hooniegit.NettyDataProtocol.Protobuf.Message.TagDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hooniegit.NettyDataProtocol.Protobuf.Message.internal_static_com_hooniegit_protobuf_TagData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hooniegit.NettyDataProtocol.Protobuf.Message.internal_static_com_hooniegit_protobuf_TagData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData.class, com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData.Builder.class);
      }

      // Construct using com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        valueCase_ = 0;
        value_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hooniegit.NettyDataProtocol.Protobuf.Message.internal_static_com_hooniegit_protobuf_TagData_descriptor;
      }

      @java.lang.Override
      public com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData getDefaultInstanceForType() {
        return com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData.getDefaultInstance();
      }

      @java.lang.Override
      public com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData build() {
        com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData buildPartial() {
        com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData result = new com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
      }

      private void buildPartialOneofs(com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData result) {
        result.valueCase_ = valueCase_;
        result.value_ = this.value_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData) {
          return mergeFrom((com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData other) {
        if (other == com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        switch (other.getValueCase()) {
          case INT_VALUE: {
            setIntValue(other.getIntValue());
            break;
          }
          case DOUBLE_VALUE: {
            setDoubleValue(other.getDoubleValue());
            break;
          }
          case STRING_VALUE: {
            valueCase_ = 4;
            value_ = other.value_;
            onChanged();
            break;
          }
          case BOOL_VALUE: {
            setBoolValue(other.getBoolValue());
            break;
          }
          case RAW_VALUE: {
            setRawValue(other.getRawValue());
            break;
          }
          case VALUE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                value_ = input.readInt32();
                valueCase_ = 2;
                break;
              } // case 16
              case 25: {
                value_ = input.readDouble();
                valueCase_ = 3;
                break;
              } // case 25
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();
                valueCase_ = 4;
                value_ = s;
                break;
              } // case 34
              case 40: {
                value_ = input.readBool();
                valueCase_ = 5;
                break;
              } // case 40
              case 50: {
                value_ = input.readBytes();
                valueCase_ = 6;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int valueCase_ = 0;
      private java.lang.Object value_;
      public ValueCase
          getValueCase() {
        return ValueCase.forNumber(
            valueCase_);
      }

      public Builder clearValue() {
        valueCase_ = 0;
        value_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      /**
       * <code>int32 int_value = 2;</code>
       * @return Whether the intValue field is set.
       */
      public boolean hasIntValue() {
        return valueCase_ == 2;
      }
      /**
       * <code>int32 int_value = 2;</code>
       * @return The intValue.
       */
      public int getIntValue() {
        if (valueCase_ == 2) {
          return (java.lang.Integer) value_;
        }
        return 0;
      }
      /**
       * <code>int32 int_value = 2;</code>
       * @param value The intValue to set.
       * @return This builder for chaining.
       */
      public Builder setIntValue(int value) {

        valueCase_ = 2;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 int_value = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIntValue() {
        if (valueCase_ == 2) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>double double_value = 3;</code>
       * @return Whether the doubleValue field is set.
       */
      public boolean hasDoubleValue() {
        return valueCase_ == 3;
      }
      /**
       * <code>double double_value = 3;</code>
       * @return The doubleValue.
       */
      public double getDoubleValue() {
        if (valueCase_ == 3) {
          return (java.lang.Double) value_;
        }
        return 0D;
      }
      /**
       * <code>double double_value = 3;</code>
       * @param value The doubleValue to set.
       * @return This builder for chaining.
       */
      public Builder setDoubleValue(double value) {

        valueCase_ = 3;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double double_value = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDoubleValue() {
        if (valueCase_ == 3) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>string string_value = 4;</code>
       * @return Whether the stringValue field is set.
       */
      @java.lang.Override
      public boolean hasStringValue() {
        return valueCase_ == 4;
      }
      /**
       * <code>string string_value = 4;</code>
       * @return The stringValue.
       */
      @java.lang.Override
      public java.lang.String getStringValue() {
        java.lang.Object ref = "";
        if (valueCase_ == 4) {
          ref = value_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (valueCase_ == 4) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string string_value = 4;</code>
       * @return The bytes for stringValue.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getStringValueBytes() {
        java.lang.Object ref = "";
        if (valueCase_ == 4) {
          ref = value_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (valueCase_ == 4) {
            value_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string string_value = 4;</code>
       * @param value The stringValue to set.
       * @return This builder for chaining.
       */
      public Builder setStringValue(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        valueCase_ = 4;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string string_value = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStringValue() {
        if (valueCase_ == 4) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string string_value = 4;</code>
       * @param value The bytes for stringValue to set.
       * @return This builder for chaining.
       */
      public Builder setStringValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        valueCase_ = 4;
        value_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>bool bool_value = 5;</code>
       * @return Whether the boolValue field is set.
       */
      public boolean hasBoolValue() {
        return valueCase_ == 5;
      }
      /**
       * <code>bool bool_value = 5;</code>
       * @return The boolValue.
       */
      public boolean getBoolValue() {
        if (valueCase_ == 5) {
          return (java.lang.Boolean) value_;
        }
        return false;
      }
      /**
       * <code>bool bool_value = 5;</code>
       * @param value The boolValue to set.
       * @return This builder for chaining.
       */
      public Builder setBoolValue(boolean value) {

        valueCase_ = 5;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool bool_value = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBoolValue() {
        if (valueCase_ == 5) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>bytes raw_value = 6;</code>
       * @return Whether the rawValue field is set.
       */
      public boolean hasRawValue() {
        return valueCase_ == 6;
      }
      /**
       * <code>bytes raw_value = 6;</code>
       * @return The rawValue.
       */
      public com.google.protobuf.ByteString getRawValue() {
        if (valueCase_ == 6) {
          return (com.google.protobuf.ByteString) value_;
        }
        return com.google.protobuf.ByteString.EMPTY;
      }
      /**
       * <code>bytes raw_value = 6;</code>
       * @param value The rawValue to set.
       * @return This builder for chaining.
       */
      public Builder setRawValue(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        valueCase_ = 6;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes raw_value = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRawValue() {
        if (valueCase_ == 6) {
          valueCase_ = 0;
          value_ = null;
          onChanged();
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.hooniegit.NettyDataProtocol.Protobuf.TagData)
    }

    // @@protoc_insertion_point(class_scope:com.hooniegit.NettyDataProtocol.Protobuf.TagData)
    private static final com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData();
    }

    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TagData>
        PARSER = new com.google.protobuf.AbstractParser<TagData>() {
      @java.lang.Override
      public TagData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TagData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TagData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TagGroupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hooniegit.NettyDataProtocol.Protobuf.TagGroup)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string timestamp = 1;</code>
     * @return The timestamp.
     */
    java.lang.String getTimestamp();
    /**
     * <code>string timestamp = 1;</code>
     * @return The bytes for timestamp.
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    /**
     * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
     */
    java.util.List<com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData> 
        getTagsList();
    /**
     * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
     */
    com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData getTags(int index);
    /**
     * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
     */
    int getTagsCount();
    /**
     * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
     */
    java.util.List<? extends com.hooniegit.NettyDataProtocol.Protobuf.Message.TagDataOrBuilder> 
        getTagsOrBuilderList();
    /**
     * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
     */
    com.hooniegit.NettyDataProtocol.Protobuf.Message.TagDataOrBuilder getTagsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.hooniegit.NettyDataProtocol.Protobuf.TagGroup}
   */
  public static final class TagGroup extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.hooniegit.NettyDataProtocol.Protobuf.TagGroup)
      TagGroupOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TagGroup.newBuilder() to construct.
    private TagGroup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TagGroup() {
      timestamp_ = "";
      tags_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TagGroup();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hooniegit.NettyDataProtocol.Protobuf.Message.internal_static_com_hooniegit_protobuf_TagGroup_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hooniegit.NettyDataProtocol.Protobuf.Message.internal_static_com_hooniegit_protobuf_TagGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup.class, com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup.Builder.class);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object timestamp_ = "";
    /**
     * <code>string timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      }
    }
    /**
     * <code>string timestamp = 1;</code>
     * @return The bytes for timestamp.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAGS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData> tags_;
    /**
     * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
     */
    @java.lang.Override
    public java.util.List<com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData> getTagsList() {
      return tags_;
    }
    /**
     * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.hooniegit.NettyDataProtocol.Protobuf.Message.TagDataOrBuilder> 
        getTagsOrBuilderList() {
      return tags_;
    }
    /**
     * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
     */
    @java.lang.Override
    public int getTagsCount() {
      return tags_.size();
    }
    /**
     * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
     */
    @java.lang.Override
    public com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData getTags(int index) {
      return tags_.get(index);
    }
    /**
     * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
     */
    @java.lang.Override
    public com.hooniegit.NettyDataProtocol.Protobuf.Message.TagDataOrBuilder getTagsOrBuilder(
        int index) {
      return tags_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timestamp_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, timestamp_);
      }
      for (int i = 0; i < tags_.size(); i++) {
        output.writeMessage(2, tags_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timestamp_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, timestamp_);
      }
      for (int i = 0; i < tags_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, tags_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup)) {
        return super.equals(obj);
      }
      com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup other = (com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup) obj;

      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
      if (!getTagsList()
          .equals(other.getTagsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
      if (getTagsCount() > 0) {
        hash = (37 * hash) + TAGS_FIELD_NUMBER;
        hash = (53 * hash) + getTagsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hooniegit.NettyDataProtocol.Protobuf.TagGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hooniegit.NettyDataProtocol.Protobuf.TagGroup)
        com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hooniegit.NettyDataProtocol.Protobuf.Message.internal_static_com_hooniegit_protobuf_TagGroup_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hooniegit.NettyDataProtocol.Protobuf.Message.internal_static_com_hooniegit_protobuf_TagGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup.class, com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup.Builder.class);
      }

      // Construct using com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        timestamp_ = "";
        if (tagsBuilder_ == null) {
          tags_ = java.util.Collections.emptyList();
        } else {
          tags_ = null;
          tagsBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hooniegit.NettyDataProtocol.Protobuf.Message.internal_static_com_hooniegit_protobuf_TagGroup_descriptor;
      }

      @java.lang.Override
      public com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup getDefaultInstanceForType() {
        return com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup.getDefaultInstance();
      }

      @java.lang.Override
      public com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup build() {
        com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup buildPartial() {
        com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup result = new com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup result) {
        if (tagsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            tags_ = java.util.Collections.unmodifiableList(tags_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.tags_ = tags_;
        } else {
          result.tags_ = tagsBuilder_.build();
        }
      }

      private void buildPartial0(com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.timestamp_ = timestamp_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup) {
          return mergeFrom((com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup other) {
        if (other == com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup.getDefaultInstance()) return this;
        if (!other.getTimestamp().isEmpty()) {
          timestamp_ = other.timestamp_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (tagsBuilder_ == null) {
          if (!other.tags_.isEmpty()) {
            if (tags_.isEmpty()) {
              tags_ = other.tags_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTagsIsMutable();
              tags_.addAll(other.tags_);
            }
            onChanged();
          }
        } else {
          if (!other.tags_.isEmpty()) {
            if (tagsBuilder_.isEmpty()) {
              tagsBuilder_.dispose();
              tagsBuilder_ = null;
              tags_ = other.tags_;
              bitField0_ = (bitField0_ & ~0x00000002);
              tagsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTagsFieldBuilder() : null;
            } else {
              tagsBuilder_.addAllMessages(other.tags_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                timestamp_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData m =
                    input.readMessage(
                        com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData.parser(),
                        extensionRegistry);
                if (tagsBuilder_ == null) {
                  ensureTagsIsMutable();
                  tags_.add(m);
                } else {
                  tagsBuilder_.addMessage(m);
                }
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object timestamp_ = "";
      /**
       * <code>string timestamp = 1;</code>
       * @return The timestamp.
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          timestamp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string timestamp = 1;</code>
       * @return The bytes for timestamp.
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        timestamp_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        timestamp_ = getDefaultInstance().getTimestamp();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string timestamp = 1;</code>
       * @param value The bytes for timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        timestamp_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.util.List<com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData> tags_ =
        java.util.Collections.emptyList();
      private void ensureTagsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          tags_ = new java.util.ArrayList<com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData>(tags_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData, com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData.Builder, com.hooniegit.NettyDataProtocol.Protobuf.Message.TagDataOrBuilder> tagsBuilder_;

      /**
       * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
       */
      public java.util.List<com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData> getTagsList() {
        if (tagsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tags_);
        } else {
          return tagsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
       */
      public int getTagsCount() {
        if (tagsBuilder_ == null) {
          return tags_.size();
        } else {
          return tagsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
       */
      public com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData getTags(int index) {
        if (tagsBuilder_ == null) {
          return tags_.get(index);
        } else {
          return tagsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
       */
      public Builder setTags(
          int index, com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.set(index, value);
          onChanged();
        } else {
          tagsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
       */
      public Builder setTags(
          int index, com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.set(index, builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
       */
      public Builder addTags(com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.add(value);
          onChanged();
        } else {
          tagsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
       */
      public Builder addTags(
          int index, com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData value) {
        if (tagsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTagsIsMutable();
          tags_.add(index, value);
          onChanged();
        } else {
          tagsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
       */
      public Builder addTags(
          com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.add(builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
       */
      public Builder addTags(
          int index, com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData.Builder builderForValue) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.add(index, builderForValue.build());
          onChanged();
        } else {
          tagsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
       */
      public Builder addAllTags(
          java.lang.Iterable<? extends com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData> values) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, tags_);
          onChanged();
        } else {
          tagsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
       */
      public Builder clearTags() {
        if (tagsBuilder_ == null) {
          tags_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          tagsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
       */
      public Builder removeTags(int index) {
        if (tagsBuilder_ == null) {
          ensureTagsIsMutable();
          tags_.remove(index);
          onChanged();
        } else {
          tagsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
       */
      public com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData.Builder getTagsBuilder(
          int index) {
        return getTagsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
       */
      public com.hooniegit.NettyDataProtocol.Protobuf.Message.TagDataOrBuilder getTagsOrBuilder(
          int index) {
        if (tagsBuilder_ == null) {
          return tags_.get(index);  } else {
          return tagsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
       */
      public java.util.List<? extends com.hooniegit.NettyDataProtocol.Protobuf.Message.TagDataOrBuilder> 
           getTagsOrBuilderList() {
        if (tagsBuilder_ != null) {
          return tagsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tags_);
        }
      }
      /**
       * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
       */
      public com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData.Builder addTagsBuilder() {
        return getTagsFieldBuilder().addBuilder(
            com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData.getDefaultInstance());
      }
      /**
       * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
       */
      public com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData.Builder addTagsBuilder(
          int index) {
        return getTagsFieldBuilder().addBuilder(
            index, com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData.getDefaultInstance());
      }
      /**
       * <code>repeated .com.hooniegit.NettyDataProtocol.Protobuf.TagData tags = 2;</code>
       */
      public java.util.List<com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData.Builder> 
           getTagsBuilderList() {
        return getTagsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData, com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData.Builder, com.hooniegit.NettyDataProtocol.Protobuf.Message.TagDataOrBuilder> 
          getTagsFieldBuilder() {
        if (tagsBuilder_ == null) {
          tagsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData, com.hooniegit.NettyDataProtocol.Protobuf.Message.TagData.Builder, com.hooniegit.NettyDataProtocol.Protobuf.Message.TagDataOrBuilder>(
                  tags_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          tags_ = null;
        }
        return tagsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.hooniegit.NettyDataProtocol.Protobuf.TagGroup)
    }

    // @@protoc_insertion_point(class_scope:com.hooniegit.NettyDataProtocol.Protobuf.TagGroup)
    private static final com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup();
    }

    public static com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TagGroup>
        PARSER = new com.google.protobuf.AbstractParser<TagGroup>() {
      @java.lang.Override
      public TagGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TagGroup> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TagGroup> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.hooniegit.NettyDataProtocol.Protobuf.Message.TagGroup getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hooniegit_protobuf_TagData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hooniegit_protobuf_TagData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hooniegit_protobuf_TagGroup_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_hooniegit_protobuf_TagGroup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\026com.hooniegit.NettyDataProtocol.Protobuf\"" +
      "\216\001\n\007TagData\022\n\n\002id\030\001 \001(\005\022\023\n\tint_value\030\002 \001" +
      "(\005H\000\022\026\n\014double_value\030\003 \001(\001H\000\022\026\n\014string_v" +
      "alue\030\004 \001(\tH\000\022\024\n\nbool_value\030\005 \001(\010H\000\022\023\n\tra" +
      "w_value\030\006 \001(\014H\000B\007\n\005value\"L\n\010TagGroup\022\021\n\t" +
      "timestamp\030\001 \001(\t\022-\n\004tags\030\002 \003(\0132\037.com.hoon" +
      "iegit.protobuf.TagDatab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_hooniegit_protobuf_TagData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hooniegit_protobuf_TagData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hooniegit_protobuf_TagData_descriptor,
        new java.lang.String[] { "Id", "IntValue", "DoubleValue", "StringValue", "BoolValue", "RawValue", "Value", });
    internal_static_com_hooniegit_protobuf_TagGroup_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hooniegit_protobuf_TagGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_hooniegit_protobuf_TagGroup_descriptor,
        new java.lang.String[] { "Timestamp", "Tags", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
